on:
  push:
    branches:
      - master
name: Update dependencies branch on master branch update

jobs:
  update_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Pull changes from master
        run: git push origin update_dependencies

